name: CI/CD for Vite React App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

# IMPORTANT: Grant GITHUB_TOKEN the permissions to deploy to GitHub Pages
permissions:
  contents: write # Crucial: Allows GITHUB_TOKEN to push to the gh-pages branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build
        # Remember: vite.config.js 'base' path might be needed:
        # base: '/your-repo-name/'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Checkout is needed for gh-pages to have a git context,
        # though gh-pages creates its own temporary repo for the 'dist' content.
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # Cache might not be strictly needed if only npx gh-pages is run from node_modules
          # cache: 'npm'

      # Ensure gh-pages is installed if it's a devDependency
      - name: Install dev dependencies (for gh-pages)
        run: npm ci # This will install devDependencies including gh-pages

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist

      # Git identity configuration is good practice for the commit gh-pages makes,
      # alternatively, use the -u flag with gh-pages
      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is used by gh-pages
        run: |
          npx gh-pages \
            --dist dist \
            --repo https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git \
            --user "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            --message "Deploy to GitHub Pages from GHA: ${{ github.sha }}" \
            --silent